#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
PHP语言处理器

提供.php文件的语法高亮支持
"""

import re
from typing import Dict, List, Any

from .base import LanguageHandler


class PHPHandler(LanguageHandler):
    """
    PHP语言处理器

    提供.php文件的语法高亮支持
    """

    # PHP文件扩展名
    file_extensions = [".php", ".phtml", ".php3", ".php4", ".php5", ".phps", ".phar"]

    def _setup_language(self):
        """
        设置PHP语言的语法高亮规则
        """
        # PHP关键字
        self._keywords = [
            # 基本关键字
            "and",
            "as",
            "break",
            "case",
            "catch",
            "class",
            "clone",
            "continue",
            "declare",
            "default",
            "do",
            "else",
            "elseif",
            "enddeclare",
            "endfor",
            "endforeach",
            "endif",
            "endswitch",
            "endwhile",
            "extends",
            "final",
            "finally",
            "for",
            "foreach",
            "function",
            "global",
            "goto",
            "if",
            "implements",
            "include",
            "include_once",
            "instanceof",
            "insteadof",
            "interface",
            "isset",
            "list",
            "namespace",
            "new",
            "or",
            "print",
            "private",
            "protected",
            "public",
            "require",
            "require_once",
            "return",
            "static",
            "switch",
            "throw",
            "trait",
            "try",
            "unset",
            "use",
            "var",
            "while",
            "xor",
            "yield",
            "yield from",
            # PHP 8+ 关键字
            "match",
            "enum",
            "readonly",
            # 魔术常量
            "__LINE__",
            "__FILE__",
            "__DIR__",
            "__FUNCTION__",
            "__CLASS__",
            "__TRAIT__",
            "__METHOD__",
            "__NAMESPACE__",
            # 魔术方法
            "__construct",
            "__destruct",
            "__call",
            "__callStatic",
            "__get",
            "__set",
            "__isset",
            "__unset",
            "__sleep",
            "__wakeup",
            "__toString",
            "__invoke",
            "__set_state",
            "__clone",
            "__debugInfo",
            "__serialize",
            "__unserialize",
            # 类型声明
            "array",
            "callable",
            "bool",
            "float",
            "int",
            "string",
            "iterable",
            "object",
            "mixed",
            "void",
            "never",
            "null",
            "false",
            "true",
            "self",
            "parent",
        ]

        # PHP内置函数和类
        self._builtins = [
            # 字符串函数
            "addslashes",
            "bin2hex",
            "chop",
            "chr",
            "chunk_split",
            "convert_cyr_string",
            "convert_uudecode",
            "convert_uuencode",
            "count_chars",
            "crc32",
            "crypt",
            "echo",
            "explode",
            "fprintf",
            "get_html_translation_table",
            "hebrev",
            "hebrevc",
            "hex2bin",
            "html_entity_decode",
            "htmlentities",
            "htmlspecialchars_decode",
            "htmlspecialchars",
            "implode",
            "join",
            "lcfirst",
            "levenshtein",
            "localeconv",
            "ltrim",
            "md5",
            "md5_file",
            "metaphone",
            "money_format",
            "nl_langinfo",
            "nl2br",
            "number_format",
            "ord",
            "parse_str",
            "print",
            "printf",
            "quoted_printable_decode",
            "quoted_printable_encode",
            "quotemeta",
            "rtrim",
            "setlocale",
            "sha1",
            "sha1_file",
            "similar_text",
            "soundex",
            "sprintf",
            "sscanf",
            "str_getcsv",
            "str_ireplace",
            "str_pad",
            "str_repeat",
            "str_replace",
            "str_rot13",
            "str_shuffle",
            "str_split",
            "str_word_count",
            "strcasecmp",
            "strchr",
            "strcmp",
            "strcoll",
            "strcspn",
            "strip_tags",
            "stripcslashes",
            "stripos",
            "stripslashes",
            "stristr",
            "strlen",
            "strnatcasecmp",
            "strnatcmp",
            "strncasecmp",
            "strncmp",
            "strpbrk",
            "strpos",
            "strrchr",
            "strrev",
            "strripos",
            "strrpos",
            "strspn",
            "strstr",
            "strtok",
            "strtolower",
            "strtoupper",
            "strtr",
            "substr_compare",
            "substr_count",
            "substr_replace",
            "substr",
            "trim",
            "ucfirst",
            "ucwords",
            "vfprintf",
            "vprintf",
            "vsprintf",
            "wordwrap",
            # 数组函数
            "array_change_key_case",
            "array_chunk",
            "array_column",
            "array_combine",
            "array_count_values",
            "array_diff_assoc",
            "array_diff_key",
            "array_diff_uassoc",
            "array_diff_ukey",
            "array_diff",
            "array_fill_keys",
            "array_fill",
            "array_filter",
            "array_flip",
            "array_intersect_assoc",
            "array_intersect_key",
            "array_intersect_uassoc",
            "array_intersect_ukey",
            "array_intersect",
            "array_key_exists",
            "array_keys",
            "array_map",
            "array_merge_recursive",
            "array_merge",
            "array_multisort",
            "array_pad",
            "array_pop",
            "array_product",
            "array_push",
            "array_rand",
            "array_reduce",
            "array_replace_recursive",
            "array_replace",
            "array_reverse",
            "array_search",
            "array_shift",
            "array_slice",
            "array_splice",
            "array_sum",
            "array_udiff_assoc",
            "array_udiff_uassoc",
            "array_udiff",
            "array_uintersect_assoc",
            "array_uintersect_uassoc",
            "array_uintersect",
            "array_unique",
            "array_unshift",
            "array_values",
            "array_walk_recursive",
            "array_walk",
            "arsort",
            "asort",
            "compact",
            "count",
            "current",
            "each",
            "end",
            "extract",
            "in_array",
            "key",
            "krsort",
            "ksort",
            "list",
            "natcasesort",
            "natsort",
            "next",
            "pos",
            "prev",
            "range",
            "reset",
            "rsort",
            "shuffle",
            "sizeof",
            "sort",
            "uasort",
            "uksort",
            "usort",
            # 数学函数
            "abs",
            "acos",
            "acosh",
            "asin",
            "asinh",
            "atan",
            "atan2",
            "atanh",
            "base_convert",
            "bindec",
            "ceil",
            "cos",
            "cosh",
            "decbin",
            "dechex",
            "decoct",
            "deg2rad",
            "exp",
            "expm1",
            "floor",
            "fmod",
            "getrandmax",
            "hexdec",
            "hypot",
            "is_finite",
            "is_infinite",
            "is_nan",
            "lcg_value",
            "log10",
            "log1p",
            "log",
            "max",
            "min",
            "mt_getrandmax",
            "mt_rand",
            "mt_srand",
            "octdec",
            "pi",
            "pow",
            "rad2deg",
            "rand",
            "round",
            "sin",
            "sinh",
            "sqrt",
            "srand",
            "tan",
            "tanh",
            # 日期时间函数
            "checkdate",
            "date_add",
            "date_create_from_format",
            "date_create_immutable_from_format",
            "date_create_immutable",
            "date_create",
            "date_date_set",
            "date_default_timezone_get",
            "date_default_timezone_set",
            "date_diff",
            "date_format",
            "date_get_last_errors",
            "date_interval_create_from_date_string",
            "date_interval_format",
            "date_isodate_set",
            "date_modify",
            "date_offset_get",
            "date_parse_from_format",
            "date_parse",
            "date_sub",
            "date_sun_info",
            "date_sunrise",
            "date_sunset",
            "date_time_set",
            "date_timestamp_get",
            "date_timestamp_set",
            "date_timezone_get",
            "date_timezone_set",
            "date",
            "getdate",
            "gettimeofday",
            "gmdate",
            "gmmktime",
            "gmstrftime",
            "idate",
            "localtime",
            "microtime",
            "mktime",
            "strftime",
            "strptime",
            "strtotime",
            "time",
            "timezone_abbreviations_list",
            "timezone_identifiers_list",
            "timezone_location_get",
            "timezone_name_from_abbr",
            "timezone_name_get",
            "timezone_offset_get",
            "timezone_open",
            "timezone_transitions_get",
            "timezone_version_get",
            # 文件系统函数
            "basename",
            "chgrp",
            "chmod",
            "chown",
            "clearstatcache",
            "copy",
            "dirname",
            "disk_free_space",
            "disk_total_space",
            "diskfreespace",
            "fclose",
            "feof",
            "fflush",
            "fgetc",
            "fgetcsv",
            "fgets",
            "fgetss",
            "file_exists",
            "file_get_contents",
            "file_put_contents",
            "file",
            "fileatime",
            "filectime",
            "filegroup",
            "fileinode",
            "filemtime",
            "fileowner",
            "fileperms",
            "filesize",
            "filetype",
            "flock",
            "fnmatch",
            "fopen",
            "fpassthru",
            "fputcsv",
            "fputs",
            "fread",
            "fscanf",
            "fseek",
            "fstat",
            "ftell",
            "ftruncate",
            "fwrite",
            "glob",
            "is_dir",
            "is_executable",
            "is_file",
            "is_link",
            "is_readable",
            "is_uploaded_file",
            "is_writable",
            "is_writeable",
            "link",
            "linkinfo",
            "lstat",
            "mkdir",
            "move_uploaded_file",
            "parse_ini_file",
            "parse_ini_string",
            "pathinfo",
            "pclose",
            "popen",
            "readfile",
            "readlink",
            "realpath_cache_get",
            "realpath",
            "rename",
            "rewind",
            "rmdir",
            "set_file_buffer",
            "stat",
            "symlink",
            "tempnam",
            "tmpfile",
            "touch",
            "umask",
            "unlink",
            # 数据库函数
            "mysqli_affected_rows",
            "mysqli_autocommit",
            "mysqli_begin_transaction",
            "mysqli_change_user",
            "mysqli_character_set_name",
            "mysqli_close",
            "mysqli_commit",
            "mysqli_connect_errno",
            "mysqli_connect_error",
            "mysqli_connect",
            "mysqli_data_seek",
            "mysqli_debug",
            "mysqli_dump_debug_info",
            "mysqli_errno",
            "mysqli_error_list",
            "mysqli_error",
            "mysqli_fetch_all",
            "mysqli_fetch_array",
            "mysqli_fetch_assoc",
            "mysqli_fetch_field_direct",
            "mysqli_fetch_field",
            "mysqli_fetch_fields",
            "mysqli_fetch_lengths",
            "mysqli_fetch_object",
            "mysqli_fetch_row",
            "mysqli_field_count",
            "mysqli_field_seek",
            "mysqli_field_tell",
            "mysqli_free_result",
            "mysqli_get_charset",
            "mysqli_get_client_info",
            "mysqli_get_client_stats",
            "mysqli_get_client_version",
            "mysqli_get_connection_stats",
            "mysqli_get_host_info",
            "mysqli_get_proto_info",
            "mysqli_get_server_info",
            "mysqli_get_server_stats",
            "mysqli_get_server_version",
            "mysqli_get_warnings",
            "mysqli_info",
            "mysqli_init",
            "mysqli_insert_id",
            "mysqli_kill",
            "mysqli_more_results",
            "mysqli_multi_query",
            "mysqli_next_result",
            "mysqli_num_fields",
            "mysqli_num_rows",
            "mysqli_options",
            "mysqli_ping",
            "mysqli_poll",
            "mysqli_prepare",
            "mysqli_query",
            "mysqli_real_connect",
            "mysqli_real_escape_string",
            "mysqli_real_query",
            "mysqli_reap_async_query",
            "mysqli_refresh",
            "mysqli_release_savepoint",
            "mysqli_report",
            "mysqli_rollback",
            "mysqli_savepoint",
            "mysqli_select_db",
            "mysqli_set_charset",
            "mysqli_set_opt",
            "mysqli_sqlstate",
            "mysqli_ssl_set",
            "mysqli_stat",
            "mysqli_stmt_affected_rows",
            "mysqli_stmt_attr_get",
            "mysqli_stmt_attr_set",
            "mysqli_stmt_bind_param",
            "mysqli_stmt_bind_result",
            "mysqli_stmt_close",
            "mysqli_stmt_data_seek",
            "mysqli_stmt_errno",
            "mysqli_stmt_error",
            "mysqli_stmt_execute",
            "mysqli_stmt_fetch",
            "mysqli_stmt_field_count",
            "mysqli_stmt_free_result",
            "mysqli_stmt_get_result",
            "mysqli_stmt_get_warnings",
            "mysqli_stmt_init",
            "mysqli_stmt_insert_id",
            "mysqli_stmt_num_rows",
            "mysqli_stmt_param_count",
            "mysqli_stmt_prepare",
            "mysqli_stmt_reset",
            "mysqli_stmt_result_metadata",
            "mysqli_stmt_send_long_data",
            "mysqli_stmt_sqlstate",
            "mysqli_stmt_store_result",
            "mysqli_store_result",
            "mysqli_thread_id",
            "mysqli_thread_safe",
            "mysqli_use_result",
            "mysqli_warning_count",
            # PDO函数
            "pdo_drivers",
            "pdo",
            # JSON函数
            "json_decode",
            "json_encode",
            "json_last_error_msg",
            "json_last_error",
            # 正则表达式函数
            "preg_filter",
            "preg_grep",
            "preg_last_error_msg",
            "preg_last_error",
            "preg_match_all",
            "preg_match",
            "preg_quote",
            "preg_replace_callback_array",
            "preg_replace_callback",
            "preg_replace",
            "preg_split",
            # URL函数
            "base64_decode",
            "base64_encode",
            "get_headers",
            "get_meta_tags",
            "http_build_query",
            "parse_url",
            "rawurldecode",
            "rawurlencode",
            "urldecode",
            "urlencode",
            # 变量函数
            "boolval",
            "debug_zval_dump",
            "doubleval",
            "empty",
            "floatval",
            "get_defined_vars",
            "get_resource_type",
            "gettype",
            "intval",
            "is_array",
            "is_bool",
            "is_callable",
            "is_countable",
            "is_double",
            "is_float",
            "is_int",
            "is_integer",
            "is_iterable",
            "is_long",
            "is_null",
            "is_numeric",
            "is_object",
            "is_real",
            "is_resource",
            "is_scalar",
            "is_string",
            "isset",
            "print_r",
            "serialize",
            "settype",
            "strval",
            "unserialize",
            "unset",
            "var_dump",
            "var_export",
            # 错误处理函数
            "debug_backtrace",
            "debug_print_backtrace",
            "error_clear_last",
            "error_get_last",
            "error_log",
            "error_reporting",
            "restore_error_handler",
            "restore_exception_handler",
            "set_error_handler",
            "set_exception_handler",
            "trigger_error",
            "user_error",
            # 会话函数
            "session_abort",
            "session_cache_expire",
            "session_cache_limiter",
            "session_commit",
            "session_create_id",
            "session_decode",
            "session_destroy",
            "session_encode",
            "session_gc",
            "session_get_cookie_params",
            "session_id",
            "session_is_registered",
            "session_module_name",
            "session_name",
            "session_regenerate_id",
            "session_register_shutdown",
            "session_register",
            "session_reset",
            "session_save_path",
            "session_set_cookie_params",
            "session_set_save_handler",
            "session_start",
            "session_status",
            "session_unregister",
            "session_unset",
            "session_write_close",
            # Cookie函数
            "setcookie",
            "setrawcookie",
            # HTTP函数
            "header",
            "header_remove",
            "headers_list",
            "headers_sent",
            "http_response_code",
            # 类和对象函数
            "class_alias",
            "class_exists",
            "get_called_class",
            "get_class_methods",
            "get_class_vars",
            "get_class",
            "get_declared_classes",
            "get_declared_interfaces",
            "get_declared_traits",
            "get_object_vars",
            "get_parent_class",
            "interface_exists",
            "is_a",
            "is_subclass_of",
            "method_exists",
            "property_exists",
            "trait_exists",
            # 命名空间函数
            "__autoload",
            "spl_autoload_call",
            "spl_autoload_extensions",
            "spl_autoload_functions",
            "spl_autoload_register",
            "spl_autoload_unregister",
            "spl_autoload",
            # 反射API
            "Reflection",
            "ReflectionClass",
            "ReflectionClassConstant",
            "ReflectionException",
            "ReflectionExtension",
            "ReflectionFunction",
            "ReflectionFunctionAbstract",
            "ReflectionGenerator",
            "ReflectionMethod",
            "ReflectionNamedType",
            "ReflectionObject",
            "ReflectionParameter",
            "ReflectionProperty",
            "ReflectionReference",
            "ReflectionType",
            "ReflectionUnionType",
            "ReflectionZendExtension",
            # 常用类
            "stdClass",
            "Exception",
            "ErrorException",
            "Throwable",
            "Generator",
            "Closure",
            "DateTime",
            "DateTimeImmutable",
            "DateTimeZone",
            "DateInterval",
            "DatePeriod",
            "Directory",
            "DirectoryIterator",
            "FilesystemIterator",
            "RecursiveDirectoryIterator",
            "GlobIterator",
            "SplFileInfo",
            "SplFileObject",
            "SplTempFileObject",
            "ArrayObject",
            "ArrayIterator",
            "RecursiveArrayIterator",
            "SplFixedArray",
            "SplObjectStorage",
            "PDO",
            "PDOStatement",
            "PDOException",
            "mysqli",
            "mysqli_stmt",
            "mysqli_result",
            "mysqli_warning",
            "mysqli_sql_exception",
            "mysqli_driver",
            "mysqli_exception",
            "SimpleXMLElement",
            "SimpleXMLIterator",
            "DOMDocument",
            "DOMNode",
            "DOMNodeList",
            "DOMElement",
            "DOMAttr",
            "DOMText",
            "DOMComment",
            "DOMProcessingInstruction",
            "DOMCdataSection",
            "DOMDocumentFragment",
            "DOMDocumentType",
            "DOMNotation",
            "DOMEntity",
            "DOMEntityReference",
            "DOMImplementation",
            "DOMNamedNodeMap",
            "DOMNameSpaceNode",
            "DOMXPath",
            "XMLReader",
            "XMLWriter",
            "XSLTProcessor",
            "SoapClient",
            "SoapServer",
            "SoapFault",
            "SoapHeader",
            "SoapParam",
            "SoapVar",
            "CURLFile",
            "curl_init",
            "curl_setopt",
            "curl_exec",
            "curl_close",
            "curl_error",
            "curl_getinfo",
            "curl_multi_init",
            "curl_multi_add_handle",
            "curl_multi_exec",
            "curl_multi_remove_handle",
            "curl_multi_close",
            "curl_multi_getcontent",
            "curl_multi_info_read",
            "curl_multi_select",
            "curl_version",
        ]

        # 正则表达式模式
        self._regex_patterns = {
            # PHP开始和结束标记
            "php_open": r"<\?php",
            "php_close": r"\?>",
            "php_short_open": r"<\?=",
            "php_asp_open": r"<\%",
            "php_asp_close": r"\%>",
            # 单行注释
            "comment": r"//.*$",
            # Shell风格注释
            "shell_comment": r"#.*$",
            # 多行注释
            "multiline_comment": r"/\*.*?\*/",
            # 文档注释
            "doc_comment": r"/\*\*.*?\*/",
            # 字符串
            "string": r'"(?:[^"\\]|\\.)*"',
            # 单引号字符串
            "single_string": r"'(?:[^'\\]|\\.)*'",
            # Heredoc
            "heredoc": r"<<[a-zA-Z_][a-zA-Z0-9_]*\n.*?\n[a-zA-Z_][a-zA-Z0-9_]*;",
            # Nowdoc
            "nowdoc": r"<<'[a-zA-Z_][a-zA-Z0-9_]*'\n.*?\n[a-zA-Z_][a-zA-Z0-9_]*;",
            # 数字
            "number": r"\b\d+\.?\d*([eE][+-]?\d+)?[fF]?\b",
            # 二进制数字
            "binary_number": r"\b0b[01_]+\b",
            # 八进制数字
            "octal_number": r"\b0[0-7_]+\b",
            # 十六进制数字
            "hex_number": r"\b0x[0-9a-fA-F_]+\b",
            # 布尔值
            "boolean": r"\b(true|false)\b",
            # null值
            "null": r"\bnull\b",
            # 变量
            "variable": r"\$[a-zA-Z_][a-zA-Z0-9_]*",
            # 类定义
            "class_def": r"\b(?:abstract\s+)?(?:final\s+)?class\s+[a-zA-Z_][a-zA-Z0-9_]*",
            # 接口定义
            "interface_def": r"\binterface\s+[a-zA-Z_][a-zA-Z0-9_]*",
            # 特质定义
            "trait_def": r"\btrait\s+[a-zA-Z_][a-zA-Z0-9_]*",
            # 枚举定义
            "enum_def": r"\benum\s+[a-zA-Z_][a-zA-Z0-9_]*",
            # 函数定义
            "function_def": r"\bfunction\s+[a-zA-Z_][a-zA-Z0-9_]*\s*\(",
            # 方法定义
            "method_def": r"\b(?:public|private|protected)?\s*(?:static\s+)?(?:final\s+)?(?:abstract\s+)?function\s+[a-zA-Z_][a-zA-Z0-9_]*\s*\(",
            # 方法调用
            "method_call": r"[a-zA-Z_][a-zA-Z0-9_]*\s*::\s*[a-zA-Z_][a-zA-Z0-9_]*\s*\(|\$[a-zA-Z_][a-zA-Z0-9_]*\s*->[a-zA-Z_][a-zA-Z0-9_]*\s*\(",
            # 属性访问
            "property_access": r"[a-zA-Z_][a-zA-Z0-9_]*\s*::\s*[a-zA-Z_][a-zA-Z0-9_]*|\$[a-zA-Z_][a-zA-Z0-9_]*\s*->[a-zA-Z_][a-zA-Z0-9_]*",
            # 命名空间
            "namespace_def": r"\bnamespace\s+[a-zA-Z_][a-zA-Z0-9_]*(?:\\[a-zA-Z_][a-zA-Z0-9_]*)*",
            # 使用命名空间
            "use_namespace": r"\buse\s+(?:function\s+)?[a-zA-Z_][a-zA-Z0-9_]*(?:\\[a-zA-Z_][a-zA-Z0-9_]*)*(?:\s+as\s+[a-zA-Z_][a-zA-Z0-9_]*)?",
            # 数组
            "array": r"array\s*\(|\[",
            # 数组访问
            "array_access": r"\$[a-zA-Z_][a-zA-Z0-9_]*\s*\[",
            # 常量定义
            "const_def": r"\bconst\s+[a-zA-Z_][a-zA-Z0-9_]*",
            # 魔术常量
            "magic_constant": r"__(LINE|FILE|DIR|FUNCTION|CLASS|TRAIT|METHOD|NAMESPACE)__",
            # 魔术方法
            "magic_method": r"__(construct|destruct|call|callStatic|get|set|isset|unset|sleep|wakeup|toString|invoke|set_state|clone|debugInfo|serialize|unserialize)",
            # 类型声明
            "type_declaration": r":\s*(?:array|callable|bool|float|int|string|iterable|object|mixed|void|never|null|self|parent|\\[a-zA-Z_][a-zA-Z0-9_]*(?:\\[a-zA-Z_][a-zA-Z0-9_]*)*)",
            # 操作符
            "operator": r"[+\-*/%=<>!&|^~?:.@]+",
            # PHP标签
            "php_tag": r"<\?(?:php|=)?|\?>",
            # HTML嵌入
            "html_embed": r"<[^?][^>]*>",
            # SQL嵌入
            "sql_embed": r"(?:SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|FROM|WHERE|JOIN|INNER|LEFT|RIGHT|OUTER|GROUP|ORDER|BY|HAVING|LIMIT|OFFSET|UNION|DISTINCT|AS|ON|AND|OR|NOT|IN|EXISTS|BETWEEN|LIKE|IS|NULL|TRUE|FALSE|CASE|WHEN|THEN|ELSE|END)\b",
        }

        # 标签样式 - 使用适合PHP语言的配色方案
        self._tag_styles = {
            "php_open": {
                "foreground": "#C586C0",
                "font": "bold",
            },  # 紫色粗体用于PHP开始标记
            "php_close": {
                "foreground": "#C586C0",
                "font": "bold",
            },  # 紫色粗体用于PHP结束标记
            "php_short_open": {
                "foreground": "#C586C0",
                "font": "bold",
            },  # 紫色粗体用于PHP短标记
            "php_asp_open": {
                "foreground": "#C586C0",
                "font": "bold",
            },  # 紫色粗体用于ASP风格标记
            "php_asp_close": {
                "foreground": "#C586C0",
                "font": "bold",
            },  # 紫色粗体用于ASP风格结束标记
            "comment": {
                "foreground": "#6A9955",
                "font": "italic",
            },  # 绿色斜体用于单行注释
            "shell_comment": {
                "foreground": "#6A9955",
                "font": "italic",
            },  # 绿色斜体用于Shell风格注释
            "multiline_comment": {
                "foreground": "#6A9955",
                "font": "italic",
            },  # 绿色斜体用于多行注释
            "doc_comment": {
                "foreground": "#608B4E",
                "font": "italic",
            },  # 深绿色斜体用于文档注释
            "string": {"foreground": "#CE9178"},  # 橙色用于字符串
            "single_string": {"foreground": "#CE9178"},  # 橙色用于单引号字符串
            "heredoc": {"foreground": "#CE9178"},  # 橙色用于Heredoc
            "nowdoc": {"foreground": "#CE9178"},  # 橙色用于Nowdoc
            "number": {"foreground": "#B5CEA8"},  # 浅绿色用于数字
            "binary_number": {"foreground": "#B5CEA8"},  # 浅绿色用于二进制数字
            "octal_number": {"foreground": "#B5CEA8"},  # 浅绿色用于八进制数字
            "hex_number": {"foreground": "#B5CEA8"},  # 浅绿色用于十六进制数字
            "boolean": {"foreground": "#569CD6"},  # 蓝色用于布尔值
            "null": {"foreground": "#569CD6"},  # 蓝色用于null值
            "variable": {"foreground": "#9CDCFE"},  # 浅蓝色用于变量
            "class_def": {
                "foreground": "#569CD6",
                "font": "bold",
            },  # 蓝色粗体用于类定义
            "interface_def": {
                "foreground": "#569CD6",
                "font": "bold",
            },  # 蓝色粗体用于接口定义
            "trait_def": {
                "foreground": "#569CD6",
                "font": "bold",
            },  # 蓝色粗体用于特质定义
            "enum_def": {
                "foreground": "#569CD6",
                "font": "bold",
            },  # 蓝色粗体用于枚举定义
            "function_def": {
                "foreground": "#DCDCAA",
                "font": "bold",
            },  # 浅黄色粗体用于函数定义
            "method_def": {
                "foreground": "#DCDCAA",
                "font": "bold",
            },  # 浅黄色粗体用于方法定义
            "method_call": {"foreground": "#DCDCAA"},  # 浅黄色用于方法调用
            "property_access": {"foreground": "#9CDCFE"},  # 浅蓝色用于属性访问
            "namespace_def": {"foreground": "#C586C0"},  # 紫色用于命名空间定义
            "use_namespace": {"foreground": "#C586C0"},  # 紫色用于使用命名空间
            "array": {"foreground": "#4EC9B0"},  # 青色用于数组
            "array_access": {"foreground": "#9CDCFE"},  # 浅蓝色用于数组访问
            "const_def": {"foreground": "#C586C0"},  # 紫色用于常量定义
            "magic_constant": {"foreground": "#FF7700"},  # 橙色用于魔术常量
            "magic_method": {"foreground": "#FF7700"},  # 橙色用于魔术方法
            "type_declaration": {"foreground": "#4EC9B0"},  # 青色用于类型声明
            "operator": {"foreground": "#D4D4D4"},  # 浅灰色用于操作符
            "php_tag": {"foreground": "#C586C0", "font": "bold"},  # 紫色粗体用于PHP标签
            "html_embed": {"foreground": "#569CD6"},  # 蓝色用于HTML嵌入
            "sql_embed": {"foreground": "#4EC9B0"},  # 青色用于SQL嵌入
        }
