#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
SQL语言处理器

提供SQL脚本的语法识别和高亮规则
"""

import re
from typing import Dict, List, Any

from .base import LanguageHandler


class SQLHandler(LanguageHandler):
    """
    SQL语言处理器

    提供SQL脚本的语法识别和高亮规则
    """

    # SQL文件扩展名
    file_extensions = [".sql", ".ddl", ".dml", ".dql", ".dcl", ".tcl"]

    def _setup_language(self):
        """设置SQL语言的语法规则"""
        # SQL关键字
        self._keywords = [
            # DDL关键字
            "CREATE",
            "ALTER",
            "DROP",
            "TRUNCATE",
            "RENAME",
            # DML关键字
            "INSERT",
            "UPDATE",
            "DELETE",
            "MERGE",
            "CALL",
            "EXPLAIN",
            "LOCK",
            # DQL关键字
            "SELECT",
            "WITH",
            # DCL关键字
            "GRANT",
            "REVOKE",
            "COMMIT",
            "ROLLBACK",
            "SAVEPOINT",
            "SET",
            "TRANSACTION",
            # TCL关键字
            "START",
            "BEGIN",
            "END",
            # 其他关键字
            "FROM",
            "WHERE",
            "GROUP",
            "BY",
            "HAVING",
            "ORDER",
            "LIMIT",
            "OFFSET",
            "UNION",
            "UNION",
            "ALL",
            "INTERSECT",
            "MINUS",
            "EXCEPT",
            "INTO",
            "VALUES",
            "AS",
            "ON",
            "USING",
            "JOIN",
            "INNER",
            "OUTER",
            "LEFT",
            "RIGHT",
            "FULL",
            "CROSS",
            "NATURAL",
            "CASE",
            "WHEN",
            "THEN",
            "ELSE",
            "END",
            "EXISTS",
            "IN",
            "ANY",
            "SOME",
            "ALL",
            "BETWEEN",
            "LIKE",
            "IS",
            "NULL",
            "TRUE",
            "FALSE",
            "UNKNOWN",
            "DISTINCT",
            "UNIQUE",
            "PRIMARY",
            "KEY",
            "FOREIGN",
            "REFERENCES",
            "CHECK",
            "DEFAULT",
            "CONSTRAINT",
            "INDEX",
            "TABLE",
            "VIEW",
            "SEQUENCE",
            "TRIGGER",
            "PROCEDURE",
            "FUNCTION",
            "PACKAGE",
            "TYPE",
            "BODY",
            "DECLARE",
            "CURSOR",
            "FOR",
            "LOOP",
            "WHILE",
            "IF",
            "ELSEIF",
            "RETURN",
            "CONTINUE",
            "BREAK",
            "GOTO",
            "EXEC",
            "EXECUTE",
            "PERFORM",
            "DO",
            "ANALYZE",
            "OPTIMIZE",
            "REPAIR",
            "SHOW",
            "DESCRIBE",
            "DESC",
            "USE",
            "DATABASE",
            "SCHEMA",
            "USER",
            "ROLE",
            "PRIVILEGES",
            "OWNER",
            "TABLESPACE",
            "TEMPORARY",
            "TEMP",
            "LOCAL",
            "GLOBAL",
            "SESSION",
            "SYSTEM",
            "PUBLIC",
            "SYNONYM",
            "MATERIALIZED",
            "LOG",
            "NOLOGGING",
            "CACHE",
            "NOCACHE",
            "INITIAL",
            "NEXT",
            "MINEXTENTS",
            "MAXEXTENTS",
            "PCTINCREASE",
            "FREELISTS",
            "FREELIST",
            "GROUPS",
            "BUFFER_POOL",
            "KEEP",
            "RECYCLE",
            "DEFAULT",
            "TABLESPACE",
            "SEGMENT",
            "EXTENT",
            "BLOCK",
            "ROW",
            "ROWID",
            "ROWNUM",
            "LEVEL",
            "PRIOR",
            "CONNECT",
            "SYSDATE",
            "USER",
            "UID",
            "CURRENT_DATE",
            "CURRENT_TIME",
            "CURRENT_TIMESTAMP",
            "LOCALTIME",
            "LOCALTIMESTAMP",
            "INTERVAL",
            "DATE",
            "TIME",
            "TIMESTAMP",
            "YEAR",
            "MONTH",
            "DAY",
            "HOUR",
            "MINUTE",
            "SECOND",
            "EXTRACT",
            "ADD_MONTHS",
            "MONTHS_BETWEEN",
            "NEXT_DAY",
            "LAST_DAY",
            "ROUND",
            "TRUNC",
            "CEIL",
            "FLOOR",
            "ABS",
            "SIGN",
            "SQRT",
            "POWER",
            "EXP",
            "LN",
            "LOG",
            "MOD",
            "REMAINDER",
            "SIN",
            "COS",
            "TAN",
            "ASIN",
            "ACOS",
            "ATAN",
            "ATAN2",
            "SINH",
            "COSH",
            "TANH",
            "DEGREES",
            "RADIANS",
            "BIN",
            "OCT",
            "HEX",
            "ASCII",
            "CHR",
            "CONCAT",
            "LOWER",
            "UPPER",
            "INITCAP",
            "LENGTH",
            "LENGTHB",
            "SUBSTR",
            "SUBSTRB",
            "INSTR",
            "INSTRB",
            "LPAD",
            "RPAD",
            "LTRIM",
            "RTRIM",
            "TRIM",
            "REPLACE",
            "TRANSLATE",
            "REGEXP_INSTR",
            "REGEXP_REPLACE",
            "REGEXP_SUBSTR",
            "REGEXP_LIKE",
            "TO_CHAR",
            "TO_DATE",
            "TO_NUMBER",
            "TO_TIMESTAMP",
            "TO_TIMESTAMP_TZ",
            "TO_YMINTERVAL",
            "TO_DSINTERVAL",
            "NUMTODSINTERVAL",
            "NUMTOYMINTERVAL",
            "CAST",
            "CONVERT",
            "DECODE",
            "NVL",
            "NVL2",
            "NULLIF",
            "COALESCE",
            "GREATEST",
            "LEAST",
            "USERENV",
            "SYS_CONTEXT",
            "SYS_GUID",
            "UID",
            "USER",
            "VSIZE",
            "DUMP",
            "RAWTOHEX",
            "HEXTORAW",
            "CHARTOROWID",
            "ROWIDTOCHAR",
            "MULTISET",
            "CARDINALITY",
            "COLLECT",
            "SET",
            "POWERMULTISET",
            "POWERMULTISET_BY",
            "CAST",
            "TREAT",
            "VALUE",
            "REF",
            "DEREF",
            "IS",
            "OF",
            "TYPE",
            "INSTANCE",
            "MEMBER",
            "STATIC",
            "FINAL",
            "INSTANTIABLE",
            "OVERRIDING",
            "NOT",
            "DETERMINISTIC",
            "PARALLEL_ENABLE",
            "PIPELINED",
            "AGGREGATE",
            "USING",
            "AUTHID",
            "CURRENT_USER",
            "DEFINER",
            "RESULT_CACHE",
            "DETERMINISTIC",
            "PIPELINED",
            "PARALLEL_ENABLE",
            "ACCESSIBLE",
            "BY",
            "CASCADE",
            "COLUMN",
            "COLUMNS",
            "CONSTRAINT",
            "CURRENT",
            "CURRENT_USER",
            "DEFERRABLE",
            "DEFERRED",
            "DEPTH",
            "DESCRIBE",
            "DOMAIN",
            "EACH",
            "ENCODING",
            "EXCEPT",
            "EXCLUDE",
            "EXCLUDING",
            "FIRST",
            "FOLLOWING",
            "FORCE",
            "GLOBAL",
            "GRANTED",
            "GROUPS",
            "HAVING",
            "HIERARCHY",
            "HOLD",
            "INCLUDE",
            "INCLUDING",
            "INHERIT",
            "INPUT",
            "INTERSECT",
            "KEY",
            "LANGUAGE",
            "LAST",
            "LEVEL",
            "LOCAL",
            "LOCATION",
            "MAP",
            "MATCHED",
            "NAME",
            "NAMES",
            "NEXT",
            "NO",
            "NOCYCLE",
            "NOMAXVALUE",
            "NOMINVALUE",
            "NONE",
            "NOWAIT",
            "OBJECT",
            "OF",
            "OFF",
            "OID",
            "OPERATOR",
            "OPTION",
            "OPTIONS",
            "ORDERING",
            "OTHERS",
            "OVER",
            "OWNER",
            "PARTITION",
            "PASSWORD",
            "PRECEDING",
            "PRIVILEGES",
            "READ",
            "RECURSIVE",
            "REF",
            "REFERENCING",
            "RENAME",
            "REPEATABLE",
            "REPLACE",
            "RESET",
            "RESTART",
            "RESTRICT",
            "RETURNING",
            "ROLE",
            "ROLLUP",
            "ROW",
            "ROWS",
            "RULE",
            "SAVEPOINT",
            "SCHEMA",
            "SCHEMAS",
            "SEARCH",
            "SECOND",
            "SECURITY",
            "SEQUENCE",
            "SEQUENCES",
            "SESSION",
            "SET",
            "SETS",
            "SHARE",
            "SIMILAR",
            "SKIP",
            "SNAPSHOT",
            "SOME",
            "START",
            "STATEMENT",
            "STATISTICS",
            "STDIN",
            "STDOUT",
            "STORAGE",
            "STRICT",
            "STRUCTURE",
            "SUBSTRING",
            "SYSTEM",
            "TABLE",
            "TABLES",
            "TABLESPACE",
            "TEMP",
            "TEMPLATE",
            "TEMPORARY",
            "THEN",
            "TIME",
            "TIMESTAMP",
            "TO",
            "TRAILING",
            "TRANSACTION",
            "TREAT",
            "TRIGGER",
            "TRUNCATE",
            "TYPE",
            "UNDER",
            "UNBOUNDED",
            "UNENCRYPTED",
            "UNIQUE",
            "UNTIL",
            "UPDATE",
            "USAGE",
            "USER",
            "USING",
            "VALID",
            "VALIDATOR",
            "VALUE",
            "VALUES",
            "VARYING",
            "VIEW",
            "WHEN",
            "WHERE",
            "WINDOW",
            "WITH",
            "WITHOUT",
            "WORK",
            "WRAPPER",
            "WRITE",
            "ZONE",
        ]

        # 数据类型
        data_types = [
            "INTEGER",
            "INT",
            "SMALLINT",
            "BIGINT",
            "DECIMAL",
            "NUMERIC",
            "REAL",
            "DOUBLE",
            "PRECISION",
            "FLOAT",
            "CHARACTER",
            "CHAR",
            "VARCHAR",
            "VARCHAR2",
            "NVARCHAR",
            "NVARCHAR2",
            "CLOB",
            "NCLOB",
            "BLOB",
            "BFILE",
            "RAW",
            "LONG",
            "LONG RAW",
            "DATE",
            "TIME",
            "TIMESTAMP",
            "INTERVAL",
            "YEAR",
            "MONTH",
            "DAY",
            "HOUR",
            "MINUTE",
            "SECOND",
            "BOOLEAN",
            "BIT",
            "BIT VARYING",
            "VARBIT",
            "TEXT",
            "BYTEA",
            "UUID",
            "JSON",
            "JSONB",
            "XML",
            "GEOMETRY",
            "POINT",
            "LINESTRING",
            "POLYGON",
            "MULTIPOINT",
            "MULTILINESTRING",
            "MULTIPOLYGON",
            "GEOMETRYCOLLECTION",
            "ENUM",
            "SET",
            "SERIAL",
            "BIGSERIAL",
            "MONEY",
            "SMALLMONEY",
            "TINYINT",
            "MEDIUMINT",
        ]

        # 正则表达式模式
        self._regex_patterns = {
            # 关键字 - 使用单词边界确保匹配完整单词
            "keywords": r"\b("
            + "|".join(re.escape(k) for k in self._keywords)
            + r")\b",
            # 数据类型
            "data_types": r"\b("
            + "|".join(re.escape(dt) for dt in data_types)
            + r")\b",
            # 注释 - 单行注释和多行注释
            "comments": r"(--.*$|/\*[\s\S]*?\*/)",
            # 字符串 - 包括单引号、双引号字符串
            "strings": r"'(?:[^']|'')*'|\"(?:[^\"\\]|\\.)*\"",
            # 数字 - 包括整数、浮点数、科学计数法
            "numbers": r"\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b",
            # 函数 - 函数名后的括号
            "functions": r"\b([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()",
            # 表名和列名 - 使用反引号、方括号或双引号括起来的标识符
            "identifiers": r"(`[^`]*`|\[[^\]]*\]|\"[^\"]*\")",
            # 操作符
            "operators": r"(\+|\-|\*|\/|%|=|==|!=|<|>|<=|>=|<>|<=>|\|\||&&|\||&|!|\(|\)|\bAND\b|\bOR\b|\bNOT\b|\bIN\b|\bEXISTS\b|\bBETWEEN\b|\bLIKE\b|\bIS\b)",
            # 变量 - @开头或:开头的变量
            "variables": r"@[a-zA-Z_][a-zA-Z0-9_]*|:[a-zA-Z_][a-zA-Z0-9_]*",
            # 占位符 - ?或:1格式
            "placeholders": r"\?|:\d+",
        }

        # 标签样式 - 使用适合SQL的配色方案
        self._tag_styles = {
            # 关键字 - 深蓝色
            "keywords": {
                "foreground": "#000080",
            },
            # 数据类型 - 蓝色
            "data_types": {
                "foreground": "#0000FF",
            },
            # 注释 - 绿色
            "comments": {
                "foreground": "#00AA00",
            },
            # 字符串 - 棕色
            "strings": {
                "foreground": "#8B4513",
            },
            # 数字 - 深红色
            "numbers": {
                "foreground": "#8B0000",
            },
            # 函数 - 紫色
            "functions": {
                "foreground": "#800080",
            },
            # 标识符 - 深青色
            "identifiers": {
                "foreground": "#008B8B",
            },
            # 操作符 - 黑色
            "operators": {
                "foreground": "#000000",
            },
            # 变量 - 深紫色
            "variables": {
                "foreground": "#4B0082",
            },
            # 占位符 - 深橙色
            "placeholders": {
                "foreground": "#FF8C00",
            },
        }
